// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./backend/models/models.js";

export function AddFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(2264495576, path);
}

export function ClearCache(): $CancellablePromise<void> {
    return $Call.ByID(1413834504);
}

export function DownloadAsset(assetID: string, filename: string): $CancellablePromise<void> {
    return $Call.ByID(4063308287, assetID, filename);
}

export function GetAccessToken(): $CancellablePromise<string> {
    return $Call.ByID(1900190090);
}

export function GetAlbumAssets(albumID: string): $CancellablePromise<models$0.Asset[] | null> {
    return $Call.ByID(92982915, albumID);
}

export function GetAlbums(): $CancellablePromise<models$0.Album[] | null> {
    return $Call.ByID(3056473311);
}

export function GetAssetInfo(assetID: string): $CancellablePromise<models$0.Asset | null> {
    return $Call.ByID(410180401, assetID);
}

export function GetAssets(): $CancellablePromise<models$0.Asset[] | null> {
    return $Call.ByID(4285129902);
}

export function GetDownloadsFolder(): $CancellablePromise<string> {
    return $Call.ByID(518210492);
}

export function GetFolders(): $CancellablePromise<string[] | null> {
    return $Call.ByID(452841144);
}

export function GetServerURL(): $CancellablePromise<string> {
    return $Call.ByID(4176951261);
}

export function GetServerVersion(): $CancellablePromise<string> {
    return $Call.ByID(3882372056);
}

export function GetStreamPort(): $CancellablePromise<number> {
    return $Call.ByID(1476922456);
}

export function GetThumbnail(assetID: string, size: string): $CancellablePromise<string | null> {
    return $Call.ByID(1359847941, assetID, size);
}

export function GetUploadQueue(): $CancellablePromise<models$0.UploadQueueItem[] | null> {
    return $Call.ByID(1742093397);
}

export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(3283000736);
}

export function Login(serverURL: string, email: string, password: string): $CancellablePromise<models$0.User | null> {
    return $Call.ByID(1387155178, serverURL, email, password);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(1110373539);
}

export function RemoveFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(58441789, path);
}

export function RetryFailed(): $CancellablePromise<void> {
    return $Call.ByID(113592032);
}

export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(237181597);
}

export function SetDownloadsFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(146618496, path);
}

export function UploadFiles(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1184827635, paths);
}
