// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./backend/models/models.js";

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function AddFolder(path) {
    return $Call.ByID(2264495576, path);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearCache() {
    return $Call.ByID(1413834504);
}

/**
 * @param {string} assetID
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function DownloadAsset(assetID, filename) {
    return $Call.ByID(4063308287, assetID, filename);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAccessToken() {
    return $Call.ByID(1900190090);
}

/**
 * @param {string} albumID
 * @returns {$CancellablePromise<models$0.Asset[]>}
 */
export function GetAlbumAssets(albumID) {
    return $Call.ByID(92982915, albumID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Album[]>}
 */
export function GetAlbums() {
    return $Call.ByID(3056473311).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} assetID
 * @returns {$CancellablePromise<models$0.Asset | null>}
 */
export function GetAssetInfo(assetID) {
    return $Call.ByID(410180401, assetID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Asset[]>}
 */
export function GetAssets() {
    return $Call.ByID(4285129902).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadsFolder() {
    return $Call.ByID(518210492);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetFolders() {
    return $Call.ByID(452841144).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetServerURL() {
    return $Call.ByID(4176951261);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetServerVersion() {
    return $Call.ByID(3882372056);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetStreamPort() {
    return $Call.ByID(1476922456);
}

/**
 * @param {string} assetID
 * @param {string} size
 * @returns {$CancellablePromise<string>}
 */
export function GetThumbnail(assetID, size) {
    return $Call.ByID(1359847941, assetID, size).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.UploadQueueItem[]>}
 */
export function GetUploadQueue() {
    return $Call.ByID(1742093397).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAuthenticated() {
    return $Call.ByID(3283000736);
}

/**
 * @param {string} serverURL
 * @param {string} email
 * @param {string} password
 * @returns {$CancellablePromise<models$0.User | null>}
 */
export function Login(serverURL, email, password) {
    return $Call.ByID(1387155178, serverURL, email, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(1110373539);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFolder(path) {
    return $Call.ByID(58441789, path);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RetryFailed() {
    return $Call.ByID(113592032);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(237181597);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetDownloadsFolder(path) {
    return $Call.ByID(146618496, path);
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function UploadFiles(paths) {
    return $Call.ByID(1184827635, paths);
}

// Private type creation functions
const $$createType0 = models$0.Asset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.Album.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Nullable($$createType0);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = models$0.UploadQueueItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.User.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
