// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Album,
    Asset,
    ExifInfo,
    UploadQueueItem,
    User
} from "./models.js";

import * as $models from "./models.js";

/**
 * Duration accepts either Immich's "H:MM:SS" string or a numeric seconds
 * value (some server versions return a number) and normalizes to a string.
 * @typedef {$models.Duration} Duration
 */
