// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Album {
    /**
     * Creates a new Album instance.
     * @param {Partial<Album>} [$$source = {}] - The source object to create the Album.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("albumName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["albumName"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("assetCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["assetCount"] = 0;
        }
        if (!("albumThumbnailAssetId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["albumThumbnailAssetId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Album}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Album(/** @type {Partial<Album>} */($$parsedSource));
    }
}

export class Asset {
    /**
     * Creates a new Asset instance.
     * @param {Partial<Asset>} [$$source = {}] - The source object to create the Asset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("originalPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalPath"] = "";
        }
        if (!("originalFileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalFileName"] = "";
        }
        if (!("checksum" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksum"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("fileCreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileCreatedAt"] = "";
        }
        if (!("fileModifiedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileModifiedAt"] = "";
        }
        if (!("localDateTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDateTime"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {Duration}
             */
            this["duration"] = "";
        }
        if (!("isFavorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFavorite"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["thumbUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ExifInfo | null | undefined}
             */
            this["exifInfo"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Asset}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exifInfo" in $$parsedSource) {
            $$parsedSource["exifInfo"] = $$createField13_0($$parsedSource["exifInfo"]);
        }
        return new Asset(/** @type {Partial<Asset>} */($$parsedSource));
    }
}

/**
 * Duration accepts either Immich's "H:MM:SS" string or a numeric seconds
 * value (some server versions return a number) and normalizes to a string.
 * @typedef {string} Duration
 */

export class ExifInfo {
    /**
     * Creates a new ExifInfo instance.
     * @param {Partial<ExifInfo>} [$$source = {}] - The source object to create the ExifInfo.
     */
    constructor($$source = {}) {
        if (!("fileSizeInByte" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSizeInByte"] = 0;
        }
        if (!("exifImageWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exifImageWidth"] = 0;
        }
        if (!("exifImageHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exifImageHeight"] = 0;
        }
        if (!("make" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["make"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("lensModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lensModel"] = "";
        }
        if (!("fNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fNumber"] = 0;
        }
        if (!("focalLength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["focalLength"] = 0;
        }
        if (!("iso" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iso"] = 0;
        }
        if (!("exposureTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exposureTime"] = "";
        }
        if (!("latitude" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["latitude"] = null;
        }
        if (!("longitude" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["longitude"] = null;
        }
        if (!("city" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["city"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("country" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["country"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExifInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExifInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExifInfo(/** @type {Partial<ExifInfo>} */($$parsedSource));
    }
}

export class UploadQueueItem {
    /**
     * Creates a new UploadQueueItem instance.
     * @param {Partial<UploadQueueItem>} [$$source = {}] - The source object to create the UploadQueueItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("retryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retryCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastAttempt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadQueueItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UploadQueueItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadQueueItem(/** @type {Partial<UploadQueueItem>} */($$parsedSource));
    }
}

export class User {
    /**
     * Creates a new User instance.
     * @param {Partial<User>} [$$source = {}] - The source object to create the User.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {User}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User(/** @type {Partial<User>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ExifInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
