// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Album {
    "id": string;
    "albumName": string;
    "description": string;
    "assetCount": number;
    "albumThumbnailAssetId": string;
}

export interface Asset {
    "id": string;
    "originalPath": string;
    "originalFileName": string;
    "checksum": string;
    "type": string;
    "fileCreatedAt": string;
    "fileModifiedAt": string;
    "localDateTime": string;
    "duration": Duration;
    "isFavorite": boolean;
    "createdAt": string;
    "updatedAt": string;
    "thumbUrl"?: string;
    "exifInfo"?: ExifInfo | null;
}

/**
 * Duration accepts either Immich's "H:MM:SS" string or a numeric seconds
 * value (some server versions return a number) and normalizes to a string.
 */
export type Duration = string;

export interface ExifInfo {
    "fileSizeInByte": number;
    "exifImageWidth": number;
    "exifImageHeight": number;
    "make": string;
    "model": string;
    "lensModel": string;
    "fNumber": number;
    "focalLength": number;
    "iso": number;
    "exposureTime": string;
    "latitude": number | null;
    "longitude": number | null;
    "city": string;
    "state": string;
    "country": string;
    "description": string;
}

export interface UploadQueueItem {
    "id": number;
    "filePath": string;
    "status": string;
    "retryCount": number;
    "lastAttempt"?: string;
    "error"?: string;
}

export interface User {
    "id": string;
    "email": string;
    "name": string;
}
