// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function DownloadAsset(arg1, arg2) {
  return window['go']['main']['App']['DownloadAsset'](arg1, arg2);
}

export function GetAccessToken() {
  return window['go']['main']['App']['GetAccessToken']();
}

export function GetAlbumAssets(arg1) {
  return window['go']['main']['App']['GetAlbumAssets'](arg1);
}

export function GetAlbums() {
  return window['go']['main']['App']['GetAlbums']();
}

export function GetAssetInfo(arg1) {
  return window['go']['main']['App']['GetAssetInfo'](arg1);
}

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetDownloadsFolder() {
  return window['go']['main']['App']['GetDownloadsFolder']();
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetServerVersion() {
  return window['go']['main']['App']['GetServerVersion']();
}

export function GetStreamPort() {
  return window['go']['main']['App']['GetStreamPort']();
}

export function GetThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2);
}

export function GetUploadQueue() {
  return window['go']['main']['App']['GetUploadQueue']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function RetryFailed() {
  return window['go']['main']['App']['RetryFailed']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetDownloadsFolder(arg1) {
  return window['go']['main']['App']['SetDownloadsFolder'](arg1);
}

export function UploadFiles(arg1) {
  return window['go']['main']['App']['UploadFiles'](arg1);
}
