// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddFolder(arg1:string):Promise<void>;

export function ClearCache():Promise<void>;

export function DownloadAsset(arg1:string,arg2:string):Promise<void>;

export function GetAccessToken():Promise<string>;

export function GetAlbumAssets(arg1:string):Promise<Array<models.Asset>>;

export function GetAlbums():Promise<Array<models.Album>>;

export function GetAssetInfo(arg1:string):Promise<models.Asset>;

export function GetAssets():Promise<Array<models.Asset>>;

export function GetDownloadsFolder():Promise<string>;

export function GetFolders():Promise<Array<string>>;

export function GetServerURL():Promise<string>;

export function GetServerVersion():Promise<string>;

export function GetStreamPort():Promise<number>;

export function GetThumbnail(arg1:string,arg2:string):Promise<Array<number>>;

export function GetUploadQueue():Promise<Array<models.UploadQueueItem>>;

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<models.User>;

export function Logout():Promise<void>;

export function RemoveFolder(arg1:string):Promise<void>;

export function RetryFailed():Promise<void>;

export function SelectFolder():Promise<string>;

export function SetDownloadsFolder(arg1:string):Promise<void>;

export function UploadFiles(arg1:Array<string>):Promise<void>;
